In [1]:
import os
import pandas as pd
from IPython.display import clear_output
%load_ext autoreload
%autoreload 2

In [2]:
from psychoanalyze import preprocess
from psychoanalyze.preprocess import Session, Curve

In [3]:
files = os.listdir('../data/0-raw')
files.remove('.ipynb_checkpoints')

In [266]:
# sessions.csv
sessions = []
curves = []
points = []
session_id = 1
curve_id = 1
for f in files:
    clear_output(wait=True)
    print(f)
    session = Session(f)
    session.clean()
    session_info = {
        'Monkey': session.monkey, 
        'Date': session.date, 
        'Filename':session.filename
    }
    session_df = pd.DataFrame([session_info])
    session_df.index.name = 'Session'
    session_curves = session_df.merge(session.split_into_curves(), on=['Monkey','Date'])
    session_curves.index.name = "Curve"
    sessions.append(session_df)
    curves.append(session_curves)
all_sessions = pd.concat(sessions, ignore_index=True,)
all_curves = pd.concat(curves, ignore_index=True).drop(columns='Filename')
all_curves.index.name = 'Curve'

t20170814.txt

TypeError: list indices must be integers or slices, not str

In [4]:
# sessions.csv
sessions = []
for f in files:
    clear_output(wait=True)
    print(f)
    session = Session(f)
    session.clean()
    sessions.append(session.data)
all_sessions = pd.concat(sessions, ignore_index=True,)

t20170814.txt

In [267]:
# all_curves.to_csv('../data/1-normalized/curves.csv')
# all_sessions.to_csv('../data/1-normalized/sessions.csv')

In [30]:
groups = all_sessions.groupby(['Monkey','Date','Ref Amp','Ref PW','Ref Freq','Ref Dur','Active Channels','Return Channels','Comp Amp','Comp PW'])['Result'].value_counts()

In [31]:
groups.unstack(fill_value=0).rename(columns={'1':'Hits','0':'Misses','2':'FAs','3':'CRs'})

Result                                                                                            Misses  \
Monkey Date     Ref Amp Ref PW Ref Freq Ref Dur Active Channels Return Channels Comp Amp Comp PW
U      20160926 0       0      0        0       8               128             1        1             0
                                                                                75       200           0
                                                                                350      200           1
                                                                                492      200           0
                                                                                1000     200           3
...                                                                                                  ...
Z      20170120 0       0      0        0       15              128             90       200           0
                                                                                110      200           0
                                                                                130      200           0
                                                                                150      200           0
                                                                                170      200           0

Result                                                                                            Hits  \
Monkey Date     Ref Amp Ref PW Ref Freq Ref Dur Active Channels Return Channels Comp Amp Comp PW
U      20160926 0       0      0        0       8               128             1        1           0
                                                                                75       200         1
                                                                                350      200         1
                                                                                492      200         1
                                                                                1000     200         6
...                                                                                                ...
Z      20170120 0       0      0        0       15              128             90       200        10
                                                                                110      200        12
                                                                                130      200        12
                                                                                150      200        11
                                                                                170      200        11

Result                                                                                            FAs  \
Monkey Date     Ref Amp Ref PW Ref Freq Ref Dur Active Channels Return Channels Comp Amp Comp PW
U      20160926 0       0      0        0       8               128             1        1          1
                                                                                75       200        0
                                                                                350      200        0
                                                                                492      200        0
                                                                                1000     200        0
...                                                                                               ...
Z      20170120 0       0      0        0       15              128             90       200        1
                                                                                110      200        0
                                                                                130      200        0
                                                                                150      200        0
                                                                                170      200        1

Result                                                                                            CRs
Monkey Date     Ref Amp Ref PW Ref Freq Ref Dur Active Channels Return Channels Comp Amp Comp PW
U      20160926 0       0      0        0       8               128             1        1          2
                                                                                75       200        0
                                                                                350      200        1
                                                                                492      200        0
                                                                                1000     200        7
...                                                                                               ...
Z      20170120 0       0      0        0       15              128             90       200       10
                                                                                110      200       13
                                                                                130      200       10
                                                                                150      200        9
                                                                                170      200        6

[9591 rows x 4 columns]

In [9]:
groups.to_csv('../data/1-normalized/sessions_curves_points.csv')

In [181]:
sessions = pd.read_csv('../data/1-normalized/sessions.csv', index_col='id')

In [15]:
groups

Result,Monkey,Date,Ref Amp,Ref PW,Ref Freq,Ref Dur,Active Channels,Return Channels,Comp Amp,Comp PW,Misses,Hits,FAs,CRs
Point,,,,,,,,,,,,,,
0,U,20160926,0,0,0,0,8,128,1,1,0,0,1,2
1,U,20160926,0,0,0,0,8,128,75,200,0,1,0,0
2,U,20160926,0,0,0,0,8,128,350,200,1,1,0,1
3,U,20160926,0,0,0,0,8,128,492,200,0,1,0,0
4,U,20160926,0,0,0,0,8,128,1000,200,3,6,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9586,Z,20170120,0,0,0,0,15,128,90,200,0,10,1,10
9587,Z,20170120,0,0,0,0,15,128,110,200,0,12,0,13
9588,Z,20170120,0,0,0,0,15,128,130,200,0,12,0,10
9589,Z,20170120,0,0,0,0,15,128,150,200,0,11,0,9
9590,Z,20170120,0,0,0,0,15,128,170,200,0,11,1,6

In [22]:
groups.groupby(['Monkey','Date','Ref Amp','Ref PW', 'Ref Freq','Ref Dur','Active Channels','Return Channels']).sum()[['FAs','CRs']]

Result                                                                           FAs  \
Monkey Date     Ref Amp Ref PW Ref Freq Ref Dur Active Channels Return Channels
U      20160926 0       0      0        0       8               128                8
       20160927 0       0      0        0       9               144               37
       20160928 0       0      0        0       8               128               37
       20160929 0       0      0        0       15              128               83
       20161003 0       0      0        0       15              64                11
...                                                                              ...
Z      20170120 0       0      0        0       15              0                  0
                                                                16                21
                                                                32                18
                                                                64                 5
                                                                128               15

Result                                                                           CRs
Monkey Date     Ref Amp Ref PW Ref Freq Ref Dur Active Channels Return Channels
U      20160926 0       0      0        0       8               128              189
       20160927 0       0      0        0       9               144              191
       20160928 0       0      0        0       8               128              201
       20160929 0       0      0        0       15              128              246
       20161003 0       0      0        0       15              64               295
...                                                                              ...
Z      20170120 0       0      0        0       15              0                  0
                                                                16               113
                                                                32               339
                                                                64               129
                                                                128              222

[1081 rows x 2 columns]